import LegalLayout, { H2, P, UL, LI, Strong, Callout } from '../../components/legal/LegalLayout'
import { COMPANY } from '../../lib/company'

export default function Risk() {
  return (
    <LegalLayout
      title="Risk Disclosure & Disclaimers"
      subtitle={`This disclosure explains the nature of ${COMPANY.product} and the risks of using it. It forms part of our Terms of Service. Please read it carefully.`}
    >
      <Callout tone="warn">
        {COMPANY.product} uses <Strong>virtual points only</Strong>. It is not real-money trading, gambling,
        investment, or financial advice. Virtual points have no monetary value and cannot be redeemed, withdrawn, or
        sold.
      </Callout>

      <H2 id="r1">1. Nature of the Service</H2>
      <P>{COMPANY.product} is an educational and entertainment prediction market. Users take YES/NO positions on future events using virtual points. Prices are generated by an automated market maker (LMSR) and reflect the collective, fluctuating estimates of participants — not verified facts or guarantees.</P>

      <H2 id="r2">2. No Financial, Investment, or Legal Advice</H2>
      <P>Nothing in the Service constitutes financial, investment, legal, tax, or other professional advice, or an offer or solicitation to buy or sell any security, commodity, or financial instrument. Prices and outcomes shown in the Service must not be relied upon for real-world decisions.</P>

      <H2 id="r3">3. No Guarantee of Accuracy</H2>
      <UL>
        <LI>Market prices may diverge from real-world probabilities and can be wrong.</LI>
        <LI>Market questions, descriptions, and resolution sources may contain errors or become outdated.</LI>
        <LI>Resolution depends on real-world events and third-party information that can change or be disputed.</LI>
      </UL>

      <H2 id="r4">4. Operational &amp; Technical Risks</H2>
      <UL>
        <LI>The Service may be interrupted, delayed, or contain bugs or pricing errors.</LI>
        <LI>Because data is stored primarily in your browser, clearing your browser, switching devices, or using private browsing can result in loss of your local balance, positions, and history.</LI>
        <LI>We may adjust, reset, void, or re-resolve markets and balances as described in the Terms and the Market Integrity Policy.</LI>
      </UL>

      <H2 id="r5">5. No Real-World Value</H2>
      <P>Virtual points, levels, ranks, achievements, and rankings are for engagement within the Service only. They confer no ownership, monetary value, or entitlement, and may be changed or removed at any time.</P>

      <H2 id="r6">6. Responsible Participation</H2>
      <P>Forecasting and competition can be engaging. Use the Service in moderation and consistent with your wellbeing. The Service is intended for users aged 18 and over.</P>

      <H2 id="r7">7. Disclaimer</H2>
      <P>To the fullest extent permitted by law, the Service is provided “as is” and “as available,” and {COMPANY.shortName} disclaims all warranties and is not liable for losses arising from your use of the Service, as further described in the Terms of Service. Some jurisdictions do not allow certain exclusions, so some may not apply to you.</P>

      <H2 id="r8">8. Questions</H2>
      <P>Contact <a href={`mailto:${COMPANY.emails.support}`} className="text-accent hover:underline">{COMPANY.emails.support}</a> with any questions about this disclosure.</P>
    </LegalLayout>
  )
}
